package sync

import (
	"fmt"
	"strings"

	"github.com/minhlucncc/mello-cli/internal/mello"
)

// RenderREADME produces a human-readable Markdown summary of a ticket (like
// `mello ticket view`) for the ticket folder's README.md. It is generated, not
// edited — edit ticket.md to change the ticket.
func RenderREADME(t mello.Ticket, columnName string) []byte {
	var b strings.Builder
	ref := t.TicketCode
	if ref == "" {
		ref = t.ID
	}
	fmt.Fprintf(&b, "# %s — %s\n\n", ref, t.Title)

	col := columnName
	if col == "" {
		col = t.ColumnName
	}
	meta(&b, "Column", col)
	meta(&b, "Members", memberNamesMD(t.AssigneeMembers()))
	meta(&b, "Labels", strings.Join(t.Labels, ", "))
	if t.CreatedAt != nil {
		meta(&b, "Created", t.CreatedAt.Format("2006-01-02 15:04"))
	}
	if t.UpdatedAt != nil {
		meta(&b, "Updated", t.UpdatedAt.Format("2006-01-02 15:04"))
	}
	meta(&b, "ID", t.ID)

	if strings.TrimSpace(t.Description) != "" {
		fmt.Fprintf(&b, "\n## Description\n\n%s\n", strings.TrimRight(t.Description, "\n"))
	}

	atts := t.AttachmentList()
	fmt.Fprintf(&b, "\n## Attachments (%d)\n\n", len(atts))
	if len(atts) == 0 {
		b.WriteString("_none_\n")
	}
	for _, a := range atts {
		if a.Size > 0 {
			fmt.Fprintf(&b, "- %s (%d bytes)\n", a.FileName(), a.Size)
		} else {
			fmt.Fprintf(&b, "- %s\n", a.FileName())
		}
	}

	fmt.Fprintf(&b, "\n## Comments (%d)\n\n", len(t.Comments))
	if len(t.Comments) == 0 {
		b.WriteString("_none_\n")
	}
	for _, cm := range t.Comments {
		author := cm.AuthorName
		if author == "" {
			author = cm.AuthorID
		}
		when := ""
		if cm.CreatedAt != nil {
			when = cm.CreatedAt.Format("2006-01-02 15:04")
		}
		fmt.Fprintf(&b, "- **%s** %s\n", dashIfEmpty(author), when)
		for _, line := range strings.Split(strings.TrimRight(cm.Body, "\n"), "\n") {
			fmt.Fprintf(&b, "  %s\n", line)
		}
	}

	if len(t.Activities) > 0 {
		fmt.Fprintf(&b, "\n## History (%d)\n\n", len(t.Activities))
		for _, h := range t.Activities {
			when := ""
			if h.CreatedAt != nil {
				when = h.CreatedAt.Format("2006-01-02 15:04")
			}
			actor := h.ActorName
			fmt.Fprintf(&b, "- %s — %s — %s\n", when, dashIfEmpty(h.Summary()), dashIfEmpty(actor))
		}
	}

	b.WriteString("\n---\n_Generated by mello — edit `ticket.md` to make changes._\n")
	return []byte(b.String())
}

func meta(b *strings.Builder, label, val string) {
	fmt.Fprintf(b, "- **%s:** %s\n", label, dashIfEmpty(val))
}

func memberNamesMD(ms mello.Members) string {
	parts := make([]string, 0, len(ms))
	for _, m := range ms {
		if m.Name != "" {
			parts = append(parts, m.Name)
		} else {
			parts = append(parts, m.ID)
		}
	}
	return strings.Join(parts, ", ")
}

func dashIfEmpty(s string) string {
	if s == "" {
		return "-"
	}
	return s
}

// Body format options for the description body. The CLI uses these to decide
// what to send to the server on push.
//
//   - omitted / "source" (default): the body is Markdown source. The CLI
//     converts it to sanitized HTML and sends it as `description_html` so the
//     web UI renders it.
//   - "html": the body is already HTML. The CLI sends it as `description_html`
//     verbatim. The CLI uses this value when it pulls a ticket whose remote
//     description_html is non-empty and stores it as the local body — the
//     round-trip is byte-stable.
//   - "plain": the body is plain text. The CLI sends it as `description` only;
//     `description_html` is not sent.
const (
	BodyFormatSource = "source" // local body is Markdown source; push converts to HTML
	BodyFormatHTML   = "html"   // local body is HTML; push sends verbatim as description_html
	BodyFormatPlain  = "plain"  // local body is plain text; push sends as description only
)

// TicketDoc is the editable view of a ticket stored in ticket.md: frontmatter
// fields plus the description body. Read-only fields (ticket code, id) are kept
// for display but ignored on push.
type TicketDoc struct {
	Ticket      string // code, read-only
	ID          string // read-only
	Title       string
	Status      string
	Assignee    string
	Labels      []string
	Column      string // column NAME (resolved to id on push)
	Description string // body below frontmatter (interpretation depends on BodyFormat)
	BodyFormat  string // "" = source (default), "html", or "plain"
}

// RenderTicket serializes a ticket to Markdown (frontmatter + body). columnName
// is the human column name for the ticket's column.
//
// If the server returned a non-empty description_html, the local body stores
// that HTML verbatim and the frontmatter gets body_format: html so the
// round-trip is byte-stable. The user can edit the HTML directly, or change
// body_format to "source" and replace the body with Markdown.
func RenderTicket(t mello.Ticket, columnName string) []byte {
	var b strings.Builder
	b.WriteString("---\n")
	writeKV(&b, "ticket", t.TicketCode)
	writeKV(&b, "id", t.ID)
	writeKV(&b, "title", t.Title)
	writeKV(&b, "status", t.Status)
	writeKV(&b, "assignee", t.AssigneeID)
	writeKV(&b, "column", columnName)
	b.WriteString("labels: " + renderList(t.Labels) + "\n")

	// Decide what the body of ticket.md holds. The server's description_html
	// is the source of truth for "rich" content; when it's present, store it
	// verbatim so the next push is lossless.
	var body string
	if t.DescriptionHTML != "" {
		writeKV(&b, "body_format", BodyFormatHTML)
		body = t.DescriptionHTML
	} else {
		body = t.Description
	}
	b.WriteString("---\n\n")
	b.WriteString(body)
	if !strings.HasSuffix(body, "\n") {
		b.WriteString("\n")
	}
	return []byte(b.String())
}

// ParseTicket reads a ticket.md back into a TicketDoc.
func ParseTicket(data []byte) (TicketDoc, error) {
	text := string(data)
	var doc TicketDoc
	if !strings.HasPrefix(text, "---") {
		// No frontmatter: treat the whole file as description.
		doc.Description = strings.TrimRight(text, "\n")
		return doc, nil
	}
	// Split off the frontmatter block between the first two "---" lines.
	rest := strings.TrimPrefix(text, "---")
	rest = strings.TrimPrefix(rest, "\n")
	end := strings.Index(rest, "\n---")
	if end < 0 {
		return doc, fmt.Errorf("frontmatter not closed with '---'")
	}
	front := rest[:end]
	body := rest[end+len("\n---"):]
	body = strings.TrimPrefix(body, "\n")
	body = strings.TrimPrefix(body, "\n") // drop the blank line after frontmatter

	for _, line := range strings.Split(front, "\n") {
		line = strings.TrimRight(line, "\r")
		if strings.TrimSpace(line) == "" {
			continue
		}
		key, val, ok := strings.Cut(line, ":")
		if !ok {
			// A `key:` (no value) at the end of a file is fine — the value is
			// just empty. But a `key` with no colon at all is malformed.
			trimmed := strings.TrimSpace(line)
			if strings.HasSuffix(trimmed, ":") {
				// Empty value: treat as the empty string.
				key = strings.TrimSuffix(trimmed, ":")
				val = `""`
			} else {
				return doc, fmt.Errorf("malformed frontmatter line: %q", line)
			}
		}
		key = strings.TrimSpace(key)
		val = strings.TrimSpace(val)
		switch key {
		case "ticket":
			doc.Ticket = unquote(val)
		case "id":
			doc.ID = unquote(val)
		case "title":
			doc.Title = unquote(val)
		case "status":
			doc.Status = unquote(val)
		case "assignee":
			doc.Assignee = unquote(val)
		case "column":
			doc.Column = unquote(val)
		case "labels":
			doc.Labels = parseList(val)
		case "body_format":
			doc.BodyFormat = unquote(val)
		}
	}
	doc.Description = strings.TrimRight(body, "\n")
	return doc, nil
}

func writeKV(b *strings.Builder, key, val string) {
	b.WriteString(key + ": " + quoteIfNeeded(val) + "\n")
}

// quoteIfNeeded wraps scalars that could confuse the minimal parser. The
// backslash is escaped first so the unquote step is unambiguous.
func quoteIfNeeded(s string) string {
	if s == "" {
		return `""`
	}
	if strings.ContainsAny(s, ":#\"'") || strings.HasPrefix(s, " ") || strings.HasSuffix(s, " ") ||
		strings.HasPrefix(s, "[") {
		// Escape backslash first, then the quote.
		escaped := strings.ReplaceAll(s, `\`, `\\`)
		escaped = strings.ReplaceAll(escaped, `"`, `\"`)
		return `"` + escaped + `"`
	}
	return s
}

func unquote(s string) string {
	if len(s) >= 2 && (s[0] == '"' && s[len(s)-1] == '"') {
		inner := s[1 : len(s)-1]
		// Unescape in the inverse order of quoteIfNeeded: handle backslash
		// sequences with a small state machine. This is a deliberately tiny
		// subset of YAML's double-quoted scalar escapes — just what the CLI
		// emits itself.
		var b strings.Builder
		for i := 0; i < len(inner); i++ {
			c := inner[i]
			if c == '\\' && i+1 < len(inner) {
				switch inner[i+1] {
				case '\\':
					b.WriteByte('\\')
					i++
					continue
				case '"':
					b.WriteByte('"')
					i++
					continue
				case 'n':
					b.WriteByte('\n')
					i++
					continue
				case 't':
					b.WriteByte('\t')
					i++
					continue
				case 'r':
					b.WriteByte('\r')
					i++
					continue
				}
			}
			b.WriteByte(c)
		}
		return b.String()
	}
	if len(s) >= 2 && (s[0] == '\'' && s[len(s)-1] == '\'') {
		return s[1 : len(s)-1]
	}
	return s
}

// renderList prints a labels list as inline-flow YAML: [a, b, c].
func renderList(items []string) string {
	if len(items) == 0 {
		return "[]"
	}
	quoted := make([]string, len(items))
	for i, it := range items {
		quoted[i] = quoteIfNeeded(it)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

// parseList accepts inline "[a, b]" form.
func parseList(val string) []string {
	val = strings.TrimSpace(val)
	val = strings.TrimPrefix(val, "[")
	val = strings.TrimSuffix(val, "]")
	if strings.TrimSpace(val) == "" {
		return nil
	}
	parts := strings.Split(val, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		if v := unquote(strings.TrimSpace(p)); v != "" {
			out = append(out, v)
		}
	}
	return out
}
