package sync

import (
	"fmt"
	"strings"

	"github.com/minhlucncc/mello-cli/internal/mello"
)

// RenderREADME produces a human-readable Markdown summary of a ticket (like
// `mello ticket view`) for the ticket folder's README.md. It is generated, not
// edited — edit ticket.md to change the ticket.
func RenderREADME(t mello.Ticket, columnName string) []byte {
	var b strings.Builder
	ref := t.TicketCode
	if ref == "" {
		ref = t.ID
	}
	fmt.Fprintf(&b, "# %s — %s\n\n", ref, t.Title)

	col := columnName
	if col == "" {
		col = t.ColumnName
	}
	meta(&b, "Column", col)
	meta(&b, "Members", memberNamesMD(t.AssigneeMembers()))
	meta(&b, "Labels", strings.Join(t.Labels, ", "))
	if t.CreatedAt != nil {
		meta(&b, "Created", t.CreatedAt.Format("2006-01-02 15:04"))
	}
	if t.UpdatedAt != nil {
		meta(&b, "Updated", t.UpdatedAt.Format("2006-01-02 15:04"))
	}
	meta(&b, "ID", t.ID)

	if strings.TrimSpace(t.Description) != "" {
		fmt.Fprintf(&b, "\n## Description\n\n%s\n", strings.TrimRight(t.Description, "\n"))
	}

	atts := t.AttachmentList()
	fmt.Fprintf(&b, "\n## Attachments (%d)\n\n", len(atts))
	if len(atts) == 0 {
		b.WriteString("_none_\n")
	}
	for _, a := range atts {
		if a.Size > 0 {
			fmt.Fprintf(&b, "- %s (%d bytes)\n", a.FileName(), a.Size)
		} else {
			fmt.Fprintf(&b, "- %s\n", a.FileName())
		}
	}

	fmt.Fprintf(&b, "\n## Comments (%d)\n\n", len(t.Comments))
	if len(t.Comments) == 0 {
		b.WriteString("_none_\n")
	}
	for _, cm := range t.Comments {
		author := cm.AuthorName
		if author == "" {
			author = cm.AuthorID
		}
		when := ""
		if cm.CreatedAt != nil {
			when = cm.CreatedAt.Format("2006-01-02 15:04")
		}
		fmt.Fprintf(&b, "- **%s** %s\n", dashIfEmpty(author), when)
		for _, line := range strings.Split(strings.TrimRight(cm.Body, "\n"), "\n") {
			fmt.Fprintf(&b, "  %s\n", line)
		}
	}

	if len(t.Activities) > 0 {
		fmt.Fprintf(&b, "\n## History (%d)\n\n", len(t.Activities))
		for _, h := range t.Activities {
			when := ""
			if h.CreatedAt != nil {
				when = h.CreatedAt.Format("2006-01-02 15:04")
			}
			actor := h.ActorName
			fmt.Fprintf(&b, "- %s — %s — %s\n", when, dashIfEmpty(h.Summary()), dashIfEmpty(actor))
		}
	}

	b.WriteString("\n---\n_Generated by mello — edit `ticket.md` to make changes._\n")
	return []byte(b.String())
}

func meta(b *strings.Builder, label, val string) {
	fmt.Fprintf(b, "- **%s:** %s\n", label, dashIfEmpty(val))
}

func memberNamesMD(ms mello.Members) string {
	parts := make([]string, 0, len(ms))
	for _, m := range ms {
		if m.Name != "" {
			parts = append(parts, m.Name)
		} else {
			parts = append(parts, m.ID)
		}
	}
	return strings.Join(parts, ", ")
}

func dashIfEmpty(s string) string {
	if s == "" {
		return "-"
	}
	return s
}

// TicketDoc is the editable view of a ticket stored in ticket.md: frontmatter
// fields plus the description body. Read-only fields (ticket code, id) are kept
// for display but ignored on push.
type TicketDoc struct {
	Ticket      string // code, read-only
	ID          string // read-only
	Title       string
	Status      string
	Assignee    string
	Labels      []string
	Column      string // column NAME (resolved to id on push)
	Description string // body below frontmatter
}

// RenderTicket serializes a ticket to Markdown (frontmatter + body). columnName
// is the human column name for the ticket's column.
func RenderTicket(t mello.Ticket, columnName string) []byte {
	var b strings.Builder
	b.WriteString("---\n")
	writeKV(&b, "ticket", t.TicketCode)
	writeKV(&b, "id", t.ID)
	writeKV(&b, "title", t.Title)
	writeKV(&b, "status", t.Status)
	writeKV(&b, "assignee", t.AssigneeID)
	writeKV(&b, "column", columnName)
	b.WriteString("labels: " + renderList(t.Labels) + "\n")
	b.WriteString("---\n\n")
	b.WriteString(t.Description)
	if !strings.HasSuffix(t.Description, "\n") {
		b.WriteString("\n")
	}
	return []byte(b.String())
}

// ParseTicket reads a ticket.md back into a TicketDoc.
func ParseTicket(data []byte) (TicketDoc, error) {
	text := string(data)
	var doc TicketDoc
	if !strings.HasPrefix(text, "---") {
		// No frontmatter: treat the whole file as description.
		doc.Description = strings.TrimRight(text, "\n")
		return doc, nil
	}
	// Split off the frontmatter block between the first two "---" lines.
	rest := strings.TrimPrefix(text, "---")
	rest = strings.TrimPrefix(rest, "\n")
	end := strings.Index(rest, "\n---")
	if end < 0 {
		return doc, fmt.Errorf("frontmatter not closed with '---'")
	}
	front := rest[:end]
	body := rest[end+len("\n---"):]
	body = strings.TrimPrefix(body, "\n")
	body = strings.TrimPrefix(body, "\n") // drop the blank line after frontmatter

	for _, line := range strings.Split(front, "\n") {
		line = strings.TrimRight(line, "\r")
		if strings.TrimSpace(line) == "" {
			continue
		}
		key, val, ok := strings.Cut(line, ":")
		if !ok {
			continue
		}
		key = strings.TrimSpace(key)
		val = strings.TrimSpace(val)
		switch key {
		case "ticket":
			doc.Ticket = unquote(val)
		case "id":
			doc.ID = unquote(val)
		case "title":
			doc.Title = unquote(val)
		case "status":
			doc.Status = unquote(val)
		case "assignee":
			doc.Assignee = unquote(val)
		case "column":
			doc.Column = unquote(val)
		case "labels":
			doc.Labels = parseList(val)
		}
	}
	doc.Description = strings.TrimRight(body, "\n")
	return doc, nil
}

func writeKV(b *strings.Builder, key, val string) {
	b.WriteString(key + ": " + quoteIfNeeded(val) + "\n")
}

// quoteIfNeeded wraps scalars that could confuse the minimal parser.
func quoteIfNeeded(s string) string {
	if s == "" {
		return `""`
	}
	if strings.ContainsAny(s, ":#\"'") || strings.HasPrefix(s, " ") || strings.HasSuffix(s, " ") ||
		strings.HasPrefix(s, "[") {
		return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"`
	}
	return s
}

func unquote(s string) string {
	if len(s) >= 2 && (s[0] == '"' && s[len(s)-1] == '"') {
		inner := s[1 : len(s)-1]
		return strings.ReplaceAll(inner, `\"`, `"`)
	}
	if len(s) >= 2 && (s[0] == '\'' && s[len(s)-1] == '\'') {
		return s[1 : len(s)-1]
	}
	return s
}

// renderList prints a labels list as inline-flow YAML: [a, b, c].
func renderList(items []string) string {
	if len(items) == 0 {
		return "[]"
	}
	quoted := make([]string, len(items))
	for i, it := range items {
		quoted[i] = quoteIfNeeded(it)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

// parseList accepts inline "[a, b]" form.
func parseList(val string) []string {
	val = strings.TrimSpace(val)
	val = strings.TrimPrefix(val, "[")
	val = strings.TrimSuffix(val, "]")
	if strings.TrimSpace(val) == "" {
		return nil
	}
	parts := strings.Split(val, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		if v := unquote(strings.TrimSpace(p)); v != "" {
			out = append(out, v)
		}
	}
	return out
}
